# Generated by Django 4.0 on 2022-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
