# Generated by Django 4.0 on 2022-12-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.CharField(max_length=50, null=True, verbose_name='size'),
        ),
    ]
