# Generated by Django 4.0 on 2022-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=500, null=True, verbose_name='notes'),
        ),
    ]
