# Generated by Django 4.0 on 2022-12-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_food_notes_order_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is_available'),
        ),
    ]
