# Generated by Django 4.0 on 2022-12-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_store_is_available_alter_food_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='volume',
        ),
    ]
