# Generated by Django 4.0 on 2022-12-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_store_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='size'),
        ),
    ]
